{% set name = "libcap" %}
{% set version = "2.78" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://mirrors.edge.kernel.org/pub/linux/libs/security/linux-privs/libcap2/{{ name }}-{{ version }}.tar.xz
  sha256: 0d621e562fd932ccf67b9660fb018e468a683d7b827541df27813228c996bb11

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('libcap', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - attr {{ attr }}

test:
  commands:
    - test -f "$PREFIX/lib/libcap.so"

about:
  home: https://directory.fsf.org/wiki/Libcap
  license: BSD-3-Clause
  license_family: BSD
  license_file: License
  summary: Implements the user-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels
  description: Implements the user-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels
  dev_url: https://git.kernel.org/pub/scm/libs/libcap/libcap.git
  doc_url: https://man7.org/linux/man-pages/man3/libcap.3.html

extra:
  recipe-maintainers:
    - scopatz
