{% set name = "libcap" %}
{% set version = "2.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://mirrors.edge.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-{{ version }}.tar.xz
  sha256: c0e70c3bcce288ada2bfe8d748e816b601590495312222e92e307cf18d6a38aa
  patches:
    # This removes the installation of static libraries
    - libcap-makefile.patch

build:
  number: 0
  skip: True  # [not linux]
  run_exports:
    - {{ pin_subpackage('libcap', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - attr

test:
  commands:
    - test -f "$PREFIX/lib/libcap.so"

about:
  home: https://directory.fsf.org/wiki/Libcap
  license: BSD-3-Clause
  license_family: BSD
  license_file: License
  summary: 'Implements the user-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels'

extra:
  recipe-maintainers:
    - scopatz
