# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "sVW/oiF49Sq3hi4ebYEraeyEFqsC0UieFmBrJoLTG/Av+1tm9a6egp7zRWV7OBUOvHApwNfE0n2bO+39lar5ja2rToOIKHcl/Gi+0G8eiWKYG3KcGof2MBguEARAQHUzFDD/klSBClsgGm6+C3Aoqo4gqwKIa1hJb6nS3WA3clwyUtSO5cAKz4WmxVelIoYp/pTGoZ/dhnDDjupFHVH9HlLec3Cln988/K7ZOxklT04GYaQIx3bqagfSme0F1MLE/a1OW9N5y8YXmEGDldV7c3Olw17EwlYpiAwWcJ2LdFPdtZZj7zRMmjlc1gH2as4JnB6oWmO929L7tcv6APJGl6WMpVDJqRKGUOZNjEgPgwHGvBnBcqhHWyZR4CUM46Y26dqosTHa1EtQDnnbVu88+K3ca+MznorQvTiK54sxgMt4Z8Dn945WdwPMS327FH5UsHWJ5x0KM/EASpfVq0zREKfMdZkZYb0/CqXfXY467E7sRItMdFAbcsYbJ9ut3/wNUvFN0WTYWCpnXYD6rdXClSKo0x8oKUdyaW6DnRJZNVIY0IM8/2ig10+wryCY4Mxa1dOww3Hqa9C6aWNFVBSWXTbsC2I+rkf70RvopeN3Mb/ooAs3pNzMnvXJbm5pIBHrdTs2/9oGa2odr6u2Z37LPgVrU+LV74hYxnP/bhH1W5Y="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  - export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi